-- =========================================================
-- AI Lead Enrichment & CRM Sync
-- Supabase / PostgreSQL Schema
-- =========================================================


-- =========================================================
-- LEADS TABLE
-- =========================================================

create table if not exists leads (
    id bigint generated by default as identity primary key,

    lead_id text not null,

    first_name text,
    last_name text,
    email text,
    company text,
    website text,
    job_title text,
    city text,
    country text,
    lead_source text,

    normalized_email text,
    normalized_company text,
    normalized_website text,

    lead_id_dedupe_key text,
    email_dedupe_key text,
    company_website_dedupe_key text,

    industry text,
    business_type text,
    recommended_service text,

    lead_score integer,
    priority text,
    qualification_status text,

    ai_confidence numeric,

    run_mode text not null default 'PRODUCTION',

    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);


-- =========================================================
-- LEAD EVENT AUDIT TABLE
-- =========================================================

create table if not exists lead_events (
    id bigint generated by default as identity primary key,

    event_type text not null,

    incoming_lead_id text,
    existing_lead_id bigint,

    email text,
    company text,

    run_mode text not null default 'PRODUCTION',

    details jsonb,

    created_at timestamptz not null default now()
);


-- =========================================================
-- GLOBAL WORKFLOW ERROR TABLE
-- =========================================================

create table if not exists workflow_errors (
    id bigint generated by default as identity primary key,

    event_type text not null default 'WORKFLOW_ERROR',

    workflow_id text,
    workflow_name text,

    execution_id text,
    execution_url text,
    execution_mode text,

    last_node_executed text,

    error_name text,
    error_message text,
    error_stack text,

    retry_of text,

    occurred_at timestamptz,

    created_at timestamptz not null default now()
);


-- =========================================================
-- DEDUPLICATION UNIQUE INDEXES
-- =========================================================

create unique index if not exists
leads_unique_lead_id_dedupe_key
on leads (lead_id_dedupe_key)
where lead_id_dedupe_key is not null;


create unique index if not exists
leads_unique_email_dedupe_key
on leads (email_dedupe_key)
where email_dedupe_key is not null;


create unique index if not exists
leads_unique_company_website_dedupe_key
on leads (company_website_dedupe_key)
where company_website_dedupe_key is not null;


-- =========================================================
-- ROW LEVEL SECURITY
-- =========================================================

alter table leads
enable row level security;

alter table lead_events
enable row level security;

alter table workflow_errors
enable row level security;